name: release

on:
  workflow_dispatch:
    inputs:
      new_version:
        description: 'npm version (major minor patch)'
        required: true

env:
  node_version: 14

jobs:
  version_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          # fetch full history so things like auto-changelog work properly
          fetch-depth: 0
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ env.node_version }}
          # setting a registry enables the NODE_AUTH_TOKEN env variable where we can set an npm token.  REQUIRED
          registry-url: 'https://registry.npmjs.org'
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
#      - name: Tests
#      - run: npm test
#      - bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
      - name: Git Config
        run: |
          git checkout package-lock.json
          git config --global user.email "rennanboni@gmail.com"
          git config --global user.name "${{ github.actor }}"
      - name: New Version
        run: npm version ${{ github.event.inputs.new_version }}
      - name: Publish Release
        run: npm run release
        env:
          GH_RELEASE_GITHUB_API_TOKEN: ${{ secrets.GH_TOKEN }} # built in actions token.  Passed tp gh-release if in use.
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}
